# Base image
FROM python:3.11-slim

# Thư mục làm việc trong container
WORKDIR /app

# Copy file requirements trước để cache
COPY requirements.txt .

# Cài thư viện
RUN pip install --no-cache-dir -r requirements.txt

# Copy toàn bộ source code
COPY . .

# Mở port
EXPOSE 8000

# Chạy FastAPI
CMD ["uvicorn", "todo_app.main:app", "--host", "0.0.0.0", "--port", "8000"]